# Generated by Django 3.2.6 on 2021-10-13 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(verbose_name='Price($)')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Device Image')),
                ('device_type', models.CharField(choices=[('LP', 'Laptop'), ('MB', 'Mobile'), ('Accessory', (('MA', 'Mobile Accessory'), ('LA', 'Laptop Accessory'))), ('OT', 'Other')], default='MB', max_length=2)),
                ('description', models.TextField(max_length=500)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
